### ISSUE TITLE
docker-compose up -d でnuxtが立ち上らない

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/auto-matching#146]
```
nuxt_1             |  error  in ./pages/index.vue
nuxt_1             | 
nuxt_1             | Module build failed: Error: Could not find file: '/app/pages/index.vue'.
nuxt_1             |     at getValidSourceFile (/app/node_modules/typescript/lib/typescript.js:107554:23)
nuxt_1             |     at Object.getEmitOutput (/app/node_modules/typescript/lib/typescript.js:108052:30)
nuxt_1             |     at Object.getEmitOutput (/app/node_modules/ts-loader/dist/instances.js:155:41)
nuxt_1             |     at getEmit (/app/node_modules/ts-loader/dist/index.js:172:35)
nuxt_1             |     at successLoader (/app/node_modules/ts-loader/dist/index.js:42:11)
nuxt_1             |     at Object.loader (/app/node_modules/ts-loader/dist/index.js:29:12)
nuxt_1             | 
nuxt_1             |  @ ./pages/index.vue 8:0-99 9:0-112
nuxt_1             |  @ ./.nuxt/router.js
nuxt_1             |  @ ./.nuxt/index.js
nuxt_1             |  @ ./.nuxt/client.js
nuxt_1             |  @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

```

**Comment by tsu-nera** [comment]
あれれ、Macでは立ち上がる。自宅のUbuntuでは立ち上がらない。

**Comment by tsu-nera** [comment]
コンテナのなかでyarn upgradeしたら立ち上った。
